version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672    #porta de troca de menssagens padrão
      - 15672:15672  #porta de acesso a interface de controle acessar pelo navegador localhost:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

volumes:
  postgres-data:

